### ISSUE TITLE
เสนอแนะ: เอาคำที่ไม่มีในพจนานุกรมออกจากคำเฉลย

### ISSUE THREAD

**Issue by PaperMonster** [narze/thwordle#22]
ก่อนหน้านี้เจอคำว่า "ทำงาน" และคำของวันนี้เป็นคำสองมาต่อกันโดยไม่เกิดความหมายใหม่ และเมื่อดูรายการคำเฉลยผ่านๆ ก็พบว่ามีหลายคำที่เป็นวลี ส่วนตัวคิดว่าควรเอาคำที่ไม่มีในพจนานุกรมออกจากคำเฉลย เพราะทำให้คำที่เป็นไปได้กว้างเกินไป

ความเห็นสนับสนุน https://twitter.com/Tadsaorn/status/1486409282799419393?s=20&t=kGAZ1wERdIlvu1vSueF3zA

**Comment by narze** [comment]
เห็นด้วยครับ 
ตอนแรกคือหาคำมาจาก word list ใน Github นี่แหละครับ คิดอยู่ว่าจะเปลี่ยนแต่ยังหาอันที่เหมาะสมไม่ได้

**Comment by PaperMonster** [comment]
ลองเลือกจาก list นี้มั้ยคะ https://github.com/nv23/thai-wordlist จำกัดที่ 5-7 ตัวอักษร แต่คงต้องมีการคัดคำออกอีก ไม่ให้พิสดารเกินไป

**Comment by narze** [comment]
@PaperMonster อันนี้คือ [dict.json](https://github.com/narze/thwordle/blob/main/src/lib/dict.json) เลยครับ :joy:
วิธีนึงที่ทำได้น่าจะเป็นการเอาแต่ละคำใน words.ts มากรองด้วย dict ก่อน (valids words must be in subset of dict) แต่ไม่รู้จะเหลือกี่คำ อาจจะต้องหาคำมาเพิ่มครับ

**Comment by narze** [comment]
Closed with #32
